name: pyyaml_include-dev

dependencies:
  - python
  - ipython
  - ipywidgets
  - nb_conda
  - pytest
  - coverage
  - twine
  - sphinx
  - pytest-runner
  - setuptools_scm
  - setuptools_scm_git_archive
  - autopep8
  - pylint
  - pyyaml
  - toml

